## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"
languageCode = 'en-gb'

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
#baseURL = "/"
publishDir = "public"

# Remote
baseURL = "https://candnwhc.co.uk/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
googleAnalytics = "G-299X1D0FEY"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

title = "Cheshire & North Wales Hawking Club"
copyright = "{year}"

[Params]
    author = 'Martyn Weber'
    description = "Join the Cheshire & North Wales Hawking Club, a vibrant community for falconry enthusiasts. Attend monthly meetings, participate in field meets, and connect with fellow falconers and bird of prey owners in Cheshire and North Wales."
    keywords = "Cheshire & North Wales Hawking Club, Cheshire and North Wales Hawking Club, Falconry Club, Falconry Community, North Wales Falconry, Cheshire Falconry, Falconry Enthusiasts, Join a Falconry Club, Cheshire, Hawking Club North Wales, Falconry Field Meet, falconry, club, hawking, falcon, hawk, field sport, bird of prey"
    logo = "images/falcon_banner.jpg"
    favicon = true
    timezone = "Europe/London"   
    copyright = "2025" 

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]

[Params.social]
#  github = ""
#  twitter = ""
#  instagram = "https://instagram.com"
#  linkedin = ""
#  telegram = ""
    facebook = "https://www.facebook.com/groups/1211552709807540/"
    email = "cheshirehawkingclub@hotmail.co.uk"
