## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"
languageCode = 'en-gb'

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
#baseURL = "/"
publishDir = "public"

# Remote
baseURL = "https://www.canwhc.co.uk/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
googleAnalytics = "G-299X1D0FEY"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

title = "Cheshire & North Wales Hawking Club"
copyright = "{year}"

[Params]
    author = 'Martyn Weber'
    description = "Join the Cheshire & North Wales Hawking Club, a vibrant community for falconry enthusiasts. Attend monthly meetings, participate in field meets, and connect with fellow falconers and bird of prey owners in Cheshire, North Wales and North West of England."
    ogdescription = "A falconry club for enthusiasts in Cheshire and North Wales."
    ogtitle = "Join the Cheshire & North Wales Hawking Club"
    keywords = "Cheshire falconry club, north wales falconry club, falconry club, hawking club, Join a Falconry Club, Falconry Field Meet, falconry, club, hawking, falcon, hawk, field sport, bird of prey, liverpool, manchester, chester, learn falconry, widnes"
    logo = "images/falcon_banner.jpg"
    favicon = true
    timezone = "Europe/London"   
    copyright = "2025" 

[Params.asset]
  ##fontawesome_css = ["css/fontawesome-minimal.css"]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]

[Params.social]
#  github = ""
#  twitter = ""
#  instagram = "https://instagram.com"
#  linkedin = ""
#  telegram = ""
    facebook = "https://www.facebook.com/groups/1211552709807540/"
    email = "cheshirehawkingclub@hotmail.co.uk"

[build]
    [build.buildStats]
        enable = true