## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Cheshire & North Wales Hawking Club"
copyright = "{year}"
languageCode = 'en-gb'

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "The website for the North Wales & Cheshire Hawking Club"
  logo = "images/falcon_banner.jpg"
  favicon = true
  timezone = "Europe/London"

[Params.social]
#  github = "https://github.com/caressofsteel/"
#  twitter = "https://twitter.com/caressofsteel_"
  email = "cheshirehawkingclub@hotmail.co.uk"
#  instagram = "https://instagram.com"
#  linkedin = "https://linkedin.com"
#  telegram = "https://telegram.org"
	facebook = "https://www.facebook.com/groups/1211552709807540/"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]